# Generated by Django 4.2.4 on 2023-09-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
    ]
